#ifndef LEXER_H
#define LEXER_H

//Assign the tokens proper names
typedef enum Token {
    TOKEN_STAR_EQUALS,
    TOKEN_SLASH_EQUALS,
    TOKEN_PERCENT_EQUALS,
    TOKEN_PLUS_EQUALS,
    TOKEN_MINUS_EQUALS,
    TOKEN_LESS_LESS_EQUALS,
    TOKEN_GREAT_GREAT_EQUALS,
    TOKEN_AMPERSAND_EQUALS,
    TOKEN_CARET_EQUALS,
    TOKEN_PIPE_EQUALS,
    TOKEN_OPEN_PARENTHESE,
    TOKEN_CLOSE_PARENTHESE,
    TOKEN_EQUALS,
    TOKEN_PIPE,
    TOKEN_AMPERSAND,
    TOKEN_PIPE_PIPE,
    TOKEN_AMPERSAND_AMPERSAND,
    TOKEN_CARET,
    TOKEN_EQUALS_EQUALS,
    TOKEN_EXCLAMATION_EQUALS,
    TOKEN_GREATER,
    TOKEN_LESS,
    TOKEN_GREATER_EQUALS,
    TOKEN_LESS_EQUALS,
    TOKEN_GREATER_GREATER,
    TOKEN_LESS_LESS,
    TOKEN_PLUS,
    TOKEN_MINUS,
    TOKEN_STAR,
    TOKEN_SLASH,
    TOKEN_PERCENT,
    TOKEN_TILDE,
    TOKEN_EXCLAMATION,

    TOKEN_INTEGER,
    TOKEN_REAL,

    TOKEN_IDENTIFIER,
    TOKEN_TRUE,
    TOKEN_FALSE,

    TOKEN_NEW_LINE,

    TOKEN_END_OF_FILE
} Token;

void OpenFile(const char* filename);

void CloseFile(void);

void Lex(void);

int CheckNext(Token check);

#endif