#ifndef LEXER_H
#define LEXER_H

typedef enum Token {
    TOKEN_ASSIGN,
    TOKEN_ADD_ASSIGN,
    TOKEN_SUBTRACT_ASSIGN,
    TOKEN_MULTIPLY_ASSIGN,
    TOKEN_DIVIDE_ASSIGN,
    TOKEN_MODULO_ASSIGN,
    TOKEN_LEFT_SHIFT_ASSIGN,
    TOKEN_RIGHT_SHIFT_ASSIGN,
    TOKEN_BITWISE_AND_ASSIGN,
    TOKEN_BITWISE_OR_ASSIGN,
    TOKEN_BITWISE_XOR_ASSIGN,
    TOKEN_OPEN_PARENTHESE,
    TOKEN_CLOSE_PARENTHESE,
    TOKEN_BITWISE_OR,
    TOKEN_BITWISE_AND,
    TOKEN_LOGICAL_OR,
    TOKEN_BITWISE_XOR,
    TOKEN_LOGICAL_AND,
    TOKEN_EQUAL,
    TOKEN_NOT_EQUAL,
    TOKEN_GREATER,
    TOKEN_LESS,
    TOKEN_GREATER_EQUAL,
    TOKEN_LESS_EQUAL,
    TOKEN_LEFT_SHIFT,
    TOKEN_RIGHT_SHIFT,
    TOKEN_MULTIPLY,
    TOKEN_DIVIDE,
    TOKEN_MODULO,
    TOKEN_ADD,
    TOKEN_SUBTRACT,
    TOKEN_BITWISE_NOT,
    TOKEN_LOGICAL_NOT,
    TOKEN_COLON,
    TOKEN_INTEGER,
    TOKEN_REAL,
    TOKEN_IF,
    TOKEN_ELSE,
    TOKEN_LOOP,
    TOKEN_IDENTIFIER,
    TOKEN_TRUE,
    TOKEN_FALSE,
    TOKEN_INDENT,
    TOKEN_DEDENT,
    TOKEN_NEW_LINE,
    TOKEN_END_OF_FILE
} Token;

void OpenFile(const char* filename);

void CloseFile(void);

void Lex(void);

int CheckNext(Token check);

#endif